FROM kapthevillain/base-images:miniconda3

COPY environment.yml /app/environment.yml
WORKDIR /app/
RUN conda env create -f environment.yml && conda clean -a -y 
ENV PATH /opt/conda/envs/wksp-prototype/bin:$PATH
RUN /bin/bash -c "source activate /opt/conda/envs/wksp-prototype"

COPY  app.py tests/ bin/run-tests.sh config/.config-test ./

ENV FLASK_PORT=8378

ENTRYPOINT [ "/bin/bash", "./run-tests.sh" ]